modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/SlimeKnights/Mantle/issues"
license="${mod_license}"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="Mantle"
    authors="${mod_authors}"
    description='''
Shared code for Slime Knights mods and others.
'''
    displayURL="https://www.curseforge.com/minecraft/mc-mods/mantle"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
